name = "zt-list"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
account_id = "b02fbc92220ae4bbf30d40dd2e5fe491"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"